server:
    port: 8080
    servlet:
        context-path: /sboard
mybatis:
    mapper-locations: classpath:mappers/**/*.xml

spring:
    application:
        name: sboard
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Password1!
        url: jdbc:mysql://127.0.0.1:3306/jboard
        username: abc1234
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
    # 이메일 설정
    mail:
        host: smtp.gmail.com
        port: 587
        username: gahui446@gmail.com
        password: bwyj apiz cjng yltd
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB
    thymeleaf:
      prefix: classpath:/templates

logging:
    file:
        name: logs/sboard.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        root: info


jwt:
    issuer: gahui446@gmail.com
    secret: eYgN3XAUp6AOJ089Il8TljMbX1W7KARC

# 파일 업로드 설정
file:
     upload:
            path: uploads/

